openapi: "3.0.2"
info:
  title: API Auth
  version: "1.0"
components:
  responses:
    name:
      description:
      content:
        application/json:
          schema:
            type: string


servers:
  - url: http://localhost:9090/api/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
