name: ci/cd process

on:
  push:
    branches:
      - 'master'

jobs:
  unit-test:
    name: unittest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: running unit test
      run: go test ./... -cover

  build-push-docker:
    name: build image and push docker hub
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: generate config
        env:
          CONFIG: ${{ secrets.APP_CONFIG }}
        run: |
          echo "$CONFIG" > ~/.env.yml
      - name: build image
        run: docker build -t 184572/altaecom:1.0
      - name: login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_SECRET}}
      - name: push docker registry
        run: docker docker push 184572/altaecom:1.0